#Global stuff
fidelius:
  sessionTimeout: 900000
  sessionTimeoutPad: 10000

server:
  servlet:
    context-path: /api/fidelius

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    active: container

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: heapdump, info, health

